fm_elfinder:
    instances:
        default:
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: true # disable if you want to manage loading of javascript and css assets manually
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                binds:
                  upload.presave:
                    - Plugin.AutoResize.onUpLoadPreSave
                plugins:
                  AutoResize:
                    enable: true
                    maxWidth: 1024
                    maxHeight: 1024
                    quality: 100 # JPEG image save quality                
                roots:       # at least one root must be defined, defines root filemanager directories
                    main:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/main
                        plugins:
                            AutoResize:
                                enable: true # For control by volume driver
                                maxWidth: 1024 # Path to Water mark image
                                maxHeight: 1024 # Margin right pixel
                                quality: 100 # JPEG image save quality                        
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 256M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }渀
                    certifications:
                        driver: LocalFileSystem
                        path: uploads/certifications
                        plugins:
                            AutoResize:
                                enable: true # For control by volume driver
                                maxWidth: 1024 # Path to Water mark image
                                maxHeight: 1024 # Margin right pixel
                                quality: 100 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 256M
                    diploma:
                        driver: LocalFileSystem
                        path: uploads/diploma
                        plugins:
                            AutoResize:
                                enable: true
                                maxWidth: 1024
                                maxHeight: 1024
                                quality: 100
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 256M
                        
                    webportfolio:
                        driver: LocalFileSystem
                        path: uploads/webportfolio
                        plugins:
                            AutoResize:
                                enable: true # For control by volume driver
                                maxWidth: 896 # Path to Water mark image
                                maxHeight: 504 # Margin right pixel
                                quality: 100 # JPEG image save quality
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 256M          
                        
                        
                        
                                                                    